### PR TITLE
Updated All Futures Market Streams, Implemented Proper Coin-Futures Handling

### PR DESCRIPTION
**Pull request by Tidone**
# PR Details

## Description

Updated all futures market streams:
- Corrected handling of `24hrMiniTicker`, `24hrTicker`, `depth`, `ORDER_TRADE_UPDATE` & `MARGIN_CALL`
- Implemented handling of `markPrice`, `continuous_kline`, `bookTicker`, `forceOrder` & `compositeIndex`,
- Implemented proper handling of coin-futures streams
  - Most of them are the same as the futures streams, but with a few added fields here and there
- Added test for all streams

## Related Issue

#26

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the 
**[CONTRIBUTING](https://github.com/LUCIT-Systems-and-Development/unicorn-fy/blob/master/CONTRIBUTING.md)** 
document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Tidone** [comment]
Plese wait a bit before you merge this.

I forgot to check & update some of the more obscure streams. I will do that in the next few days.

**Comment by oliver-zehentleitner** [comment]
thanks for the updates, sure i wait :)

**Comment by Tidone** [comment]
This PR is now ready.

I checked & updated all futures streams.
I also properly implemented all coin-futures streams.

**Comment by Tidone** [comment]
The explicit call to .keys() is not only not necessary but will also be much slower because a new list of all keys is generated and searched linearly, instead of using the dictionary's hashing algorithm.

`in` checks if a key is in a dictionary:
`if 'key' in dict:`

 If you want to check the values too you have to explicitly call .values():
`if 'value' in dict.values():`

Also see these [SO answers](https://stackoverflow.com/a/1602964).

**Comment by oliver-zehentleitner** [comment]
Cool, I did not expect this:

```
d = {'a': 1, 'b': 2}

if 'a' in d:
    print(f"Key found!")

if '2' in d:
    print(f"Value found!")
```

Thank you!

**Comment by Tidone** [comment]
Btw, both PRs are ready to be merged.

**Comment by oliver-zehentleitner** [comment]
Thanks again and sorry it took so long, but the UNICORN Binance Suite has become a full-time job and I only now have the resources for further development.

**Review by oliver-zehentleitner — APPROVED** [review]

**Pull request merged**
